// Data store for ARDA Seeds Reporting System
// In a real application, this would be connected to a database

export type MetricStatus = "green" | "amber" | "red";

export interface Comment {
  id: string;
  author: string;
  content: string;
  timestamp: string;
}

export interface MetricData {
  id: string;
  name: string;
  value: number | string;
  unit?: string;
  target?: number;
  previousValue?: number | string;
  status?: MetricStatus;
  trend?: "up" | "down" | "stable";
  comments: Comment[];
  details?: string;
  lastUpdated: string;
}

export interface DepartmentData {
  id: string;
  name: string;
  shortName: string;
  icon: string;
  metrics: MetricData[];
  head: string;
}

// MD Comments - comments from Managing Director to departments
export interface MDComment {
  id: string;
  departmentId: string;
  metricId?: string; // Optional - if targeting a specific metric
  content: string;
  timestamp: string;
  isRead: boolean;
}

// Static timestamp for initial data (avoids hydration mismatch)
const STATIC_TIMESTAMP = "2026-03-30T09:00:00.000Z";

// Initial MD Comments (sample data)
export const initialMDComments: MDComment[] = [
  {
    id: "md-comment-1",
    departmentId: "operations-agronomy",
    metricId: "agro-hectares",
    content: "Please provide a detailed recovery plan for the delayed planting in Section B. I need this addressed urgently.",
    timestamp: "2026-03-30T21:00:00.000Z",
    isRead: false,
  },
  {
    id: "md-comment-2",
    departmentId: "operations-manufacturing",
    metricId: "mfg-downtime",
    content: "The downtime hours are concerning. Schedule a meeting to discuss preventive maintenance improvements.",
    timestamp: "2026-03-29T09:00:00.000Z",
    isRead: true,
  },
  {
    id: "md-comment-3",
    departmentId: "sales-marketing",
    content: "Overall sales performance is tracking well. Let's push for exceeding Q4 targets.",
    timestamp: "2026-03-28T09:00:00.000Z",
    isRead: false,
  },
  {
    id: "md-comment-4",
    departmentId: "hr",
    metricId: "hr-overtime",
    content: "Overtime costs are too high. Please investigate and propose a staffing optimization plan.",
    timestamp: "2026-03-27T09:00:00.000Z",
    isRead: true,
  },
];

// Initial mock data
export const initialDepartments: DepartmentData[] = [
  {
    id: "executive",
    name: "Executive Overview",
    shortName: "Executive",
    icon: "LayoutDashboard",
    head: "Managing Director",
    metrics: [
      {
        id: "exec-revenue",
        name: "Total Revenue (YTD)",
        value: 2450000,
        unit: "USD",
        target: 3000000,
        previousValue: 2100000,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "exec-gross-profit",
        name: "Gross Profit",
        value: 735000,
        unit: "USD",
        target: 900000,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "exec-net-profit",
        name: "Net Profit",
        value: 367500,
        unit: "USD",
        target: 450000,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "exec-sales-volume",
        name: "Total Sales Volume",
        value: 1250,
        unit: "tonnes",
        target: 1500,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "exec-production-alignment",
        name: "Production vs Sales Alignment",
        value: 87,
        unit: "%",
        target: 95,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "exec-inventory-value",
        name: "Inventory Value",
        value: 450000,
        unit: "USD",
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "exec-cash-flow",
        name: "Cash Flow Status",
        value: 125000,
        unit: "USD",
        status: "green",
        trend: "up",
        details: "Inflow: $250,000 | Outflow: $125,000",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "exec-debtors",
        name: "Debtors vs Creditors",
        value: "320K / 180K",
        unit: "USD",
        status: "amber",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "exec-top-product",
        name: "Top Performing Product",
        value: "SC 719 Maize",
        status: "green",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
    ],
  },
  {
    id: "operations-agronomy",
    name: "Operations - Agronomy",
    shortName: "Agronomy",
    icon: "Wheat",
    head: "Agronomy Manager",
    metrics: [
      {
        id: "agro-hectares",
        name: "Total Hectares Planted vs Planned",
        value: "850 / 1000",
        unit: "ha",
        status: "amber",
        trend: "up",
        comments: [
          {
            id: "c1",
            author: "Agronomy Manager",
            content: "Delayed planting in Section B due to late rains. Expecting to catch up next week.",
            timestamp: "2026-03-29T09:00:00.000Z",
          },
        ],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "agro-yield",
        name: "Expected Yield vs Actual",
        value: "4200 / 3800",
        unit: "tonnes",
        status: "amber",
        trend: "down",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "agro-yield-per-ha",
        name: "Yield per Hectare",
        value: 4.5,
        unit: "tonnes/ha",
        target: 5,
        status: "amber",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "agro-crop-progress",
        name: "Crop Progress Status",
        value: "Flowering Stage",
        status: "green",
        details: "75% of crops at flowering stage, 25% at vegetative stage",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "agro-variety-performance",
        name: "Seed Variety Performance",
        value: "SC 719: Excellent",
        status: "green",
        details: "SC 719: Excellent | SC 513: Good | SC 403: Average",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "agro-input-cost",
        name: "Input Cost per Hectare",
        value: 450,
        unit: "USD/ha",
        target: 400,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "agro-weather-risk",
        name: "Weather Impact Risk",
        value: "Moderate",
        status: "amber",
        details: "Drought risk in eastern region. Irrigation systems operational.",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
    ],
  },
  {
    id: "operations-manufacturing",
    name: "Operations - Manufacturing",
    shortName: "Manufacturing",
    icon: "Factory",
    head: "Manufacturing Manager",
    metrics: [
      {
        id: "mfg-raw-received",
        name: "Raw Seed Received",
        value: 3200,
        unit: "tonnes",
        status: "green",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "mfg-processed-output",
        name: "Processed Seed Output",
        value: 2850,
        unit: "tonnes",
        status: "green",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "mfg-packaged",
        name: "Packaged Seed",
        value: 2700,
        unit: "tonnes",
        status: "green",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "mfg-dispatch",
        name: "Dispatch Volume",
        value: 2500,
        unit: "tonnes",
        status: "green",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "mfg-efficiency",
        name: "Processing Efficiency",
        value: 89,
        unit: "%",
        target: 95,
        status: "amber",
        trend: "up",
        comments: [
          {
            id: "c2",
            author: "Manufacturing Manager",
            content: "New calibration on sorting machines improved efficiency by 3%.",
            timestamp: "2026-03-28T09:00:00.000Z",
          },
        ],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "mfg-downtime",
        name: "Downtime",
        value: 12,
        unit: "hours",
        target: 8,
        status: "red",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "mfg-cost-per-tonne",
        name: "Cost per Tonne Processed",
        value: 85,
        unit: "USD",
        target: 80,
        status: "amber",
        trend: "down",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "mfg-waste-rate",
        name: "Waste/Reject Rate",
        value: 4.2,
        unit: "%",
        target: 3,
        status: "red",
        trend: "down",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "mfg-finished-warehouse",
        name: "Finished Product in Warehouse",
        value: 1800,
        unit: "tonnes",
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
    ],
  },
  {
    id: "sales-marketing",
    name: "Sales & Marketing",
    shortName: "Sales",
    icon: "TrendingUp",
    head: "Sales Manager",
    metrics: [
      {
        id: "sales-revenue",
        name: "Total Sales Revenue (YTD)",
        value: 2450000,
        unit: "USD",
        target: 3000000,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "sales-volume-variety",
        name: "Sales Volume by Variety",
        value: "SC 719: 45%",
        details: "SC 719: 45% | SC 513: 30% | SC 403: 15% | Others: 10%",
        status: "green",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "sales-regional",
        name: "Regional Sales Performance",
        value: "North: 35%",
        details: "North: 35% | South: 28% | East: 22% | West: 15%",
        status: "green",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "sales-target-actual",
        name: "Sales Target vs Actual",
        value: 82,
        unit: "%",
        target: 100,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "sales-top-customers",
        name: "Top Customers",
        value: "AgriCorp Ltd",
        details: "1. AgriCorp Ltd | 2. FarmFirst | 3. GreenFields | 4. SeedMart",
        status: "green",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "sales-acquisition",
        name: "Customer Acquisition Rate",
        value: 15,
        unit: "new/month",
        target: 20,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "sales-repeat",
        name: "Repeat Purchase Rate",
        value: 78,
        unit: "%",
        target: 80,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "sales-marketing-roi",
        name: "Marketing Campaign ROI",
        value: 3.2,
        unit: "x",
        target: 4,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "sales-lead-conversion",
        name: "Lead Conversion Rate",
        value: 24,
        unit: "%",
        target: 30,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "sales-pricing",
        name: "Pricing vs Competitors",
        value: "Competitive",
        details: "5% below market average on premium varieties",
        status: "green",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
    ],
  },
  {
    id: "finance",
    name: "Finance",
    shortName: "Finance",
    icon: "DollarSign",
    head: "Finance Manager",
    metrics: [
      {
        id: "fin-revenue-expenses",
        name: "Revenue vs Expenses",
        value: "2.45M / 1.72M",
        unit: "USD",
        status: "green",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-gross-margin",
        name: "Gross Margin",
        value: 30,
        unit: "%",
        target: 35,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-net-margin",
        name: "Net Margin",
        value: 15,
        unit: "%",
        target: 18,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-cash-flow",
        name: "Cash Flow",
        value: 125000,
        unit: "USD",
        details: "Operating: $180K | Investing: -$30K | Financing: -$25K",
        status: "green",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-inventory-levels",
        name: "Inventory Levels",
        value: "ZS269",
        unit: "850 tonnes",
        details:
          "2nd: OPV maize ZM521 (720 t) · 3rd: Msasa (580 t) · 4th: SORGHUM Macia (390 t)",
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-inventory-turnover",
        name: "Inventory Turnover Ratio",
        value: 4.2,
        unit: "x",
        target: 5,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-debtors-aging",
        name: "Accounts Receivable (Aging)",
        value: "320K (45 days)",
        unit: "USD",
        status: "amber",
        details: "0-30 days: $180K | 31-60 days: $100K | 60+: $40K",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-creditors-aging",
        name: "Accounts Payable (Aging)",
        value: "180K (30 days)",
        unit: "USD",
        status: "green",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-budget-actual",
        name: "Budget vs Actual Spend",
        value: 92,
        unit: "%",
        target: 100,
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-cost-breakdown",
        name: "Cost Breakdown",
        value: "Operations: 45%",
        details: "Operations: 45% | Salaries: 30% | Logistics: 15% | Other: 10%",
        status: "green",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-profitability",
        name: "Profitability by Product",
        value: "SC 719: 38%",
        details: "SC 719: 38% | SC 513: 32% | SC 403: 28%",
        status: "green",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-working-capital",
        name: "Working Capital",
        value: 280000,
        unit: "USD",
        status: "green",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "fin-risk-indicators",
        name: "Financial Risk Indicators",
        value: "Low",
        status: "green",
        details: "Debt ratio: 0.3 | Current ratio: 1.8 | Quick ratio: 1.2",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
    ],
  },
  {
    id: "hr",
    name: "Human Resources",
    shortName: "HR",
    icon: "Users",
    head: "HR Manager",
    metrics: [
      {
        id: "hr-headcount",
        name: "Total Workforce Headcount",
        value: 245,
        unit: "employees",
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "hr-turnover",
        name: "Staff Turnover Rate",
        value: 8,
        unit: "%",
        target: 10,
        status: "green",
        trend: "down",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "hr-attendance",
        name: "Attendance Rate",
        value: 94,
        unit: "%",
        target: 95,
        status: "amber",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "hr-productivity",
        name: "Employee Productivity",
        value: 12.5,
        unit: "tonnes/employee",
        target: 14,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "hr-training",
        name: "Training Hours (YTD)",
        value: 2400,
        unit: "hours",
        target: 3000,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "hr-payroll-ratio",
        name: "Payroll Costs vs Revenue",
        value: 18,
        unit: "%",
        target: 20,
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "hr-satisfaction",
        name: "Employee Satisfaction Score",
        value: 7.8,
        unit: "/10",
        target: 8,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "hr-overtime",
        name: "Overtime Costs",
        value: 15000,
        unit: "USD/month",
        target: 12000,
        status: "red",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "hr-staffing",
        name: "Staffing Levels vs Requirements",
        value: "92%",
        status: "amber",
        details: "Operations: 95% | Admin: 90% | Sales: 88%",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
    ],
  },
  {
    id: "procurement",
    name: "Procurement / Supply Chain",
    shortName: "Procurement",
    icon: "ShoppingCart",
    head: "Procurement Manager",
    metrics: [
      {
        id: "proc-capex",
        name: "Capex Expenditure",
        value: 180000,
        unit: "USD",
        target: 200000,
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "proc-opex",
        name: "Opex Expenditure",
        value: 520000,
        unit: "USD",
        target: 500000,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "proc-total",
        name: "Total Expenditure",
        value: 700000,
        unit: "USD",
        target: 700000,
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "proc-credit",
        name: "Credit Purchases",
        value: 420000,
        unit: "USD",
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "proc-cash",
        name: "Cash Purchases",
        value: 280000,
        unit: "USD",
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "proc-input-status",
        name: "Input Availability Status",
        value: "Good",
        details: "Seeds: 95% | Chemicals: 88% | Packaging: 92%",
        status: "green",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "proc-reorder",
        name: "Stock Reorder Alerts",
        value: 3,
        unit: "items",
        status: "amber",
        details: "Packaging bags (low) | Fertilizer Type A (critical) | Labels (low)",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "proc-savings",
        name: "Cost Savings Achieved",
        value: 45000,
        unit: "USD",
        target: 50000,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
    ],
  },
  {
    id: "ict",
    name: "ICT and Digital Transformation",
    shortName: "ICT",
    icon: "Monitor",
    head: "ICT Manager",
    metrics: [
      {
        id: "ict-uptime",
        name: "Systems Uptime",
        value: 99.2,
        unit: "%",
        target: 99.5,
        status: "amber",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "ict-licenses",
        name: "Active Microsoft License Users",
        value: 185,
        unit: "users",
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "ict-support",
        name: "IT Support Issues Resolved",
        value: "45 / 48",
        status: "green",
        trend: "up",
        details: "Average resolution time: 4.2 hours",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "ict-internet",
        name: "Internet Infrastructure",
        value: "Operational",
        status: "green",
        details: "Primary: 100Mbps fiber | Backup: 50Mbps LTE",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "ict-security",
        name: "Cybersecurity Alerts",
        value: 2,
        unit: "alerts",
        status: "amber",
        details: "2 medium-priority alerts under investigation",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "ict-projects",
        name: "Project Progress",
        value: 68,
        unit: "%",
        target: 75,
        status: "amber",
        details: "ERP Phase 2: 72% | Mobile App: 65% | Data Analytics: 68%",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
    ],
  },
  {
    id: "inventory",
    name: "Inventory / Warehouse",
    shortName: "Inventory",
    icon: "Warehouse",
    head: "Warehouse Manager",
    metrics: [
      {
        id: "inv-stock-levels",
        name: "Current Stock Levels",
        value: 2800,
        unit: "tonnes",
        status: "green",
        details: "SC 719: 1200t | SC 513: 900t | SC 403: 500t | Others: 200t",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "inv-stock-value",
        name: "Stock Value",
        value: 450000,
        unit: "USD",
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "inv-movement",
        name: "Stock Movement (Monthly)",
        value: "In: 850t / Out: 780t",
        status: "green",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "inv-slow-moving",
        name: "Slow-moving / Dead Stock",
        value: 120,
        unit: "tonnes",
        status: "amber",
        trend: "down",
        details: "SC 301 (discontinued): 80t | Damaged stock: 40t",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "inv-capacity",
        name: "Storage Capacity Utilization",
        value: 72,
        unit: "%",
        target: 80,
        status: "green",
        trend: "stable",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "inv-expiry-risk",
        name: "Expiry Risk",
        value: "Low",
        status: "green",
        details: "No stock expiring within 6 months",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "inv-turnover",
        name: "Inventory Turnover",
        value: 4.2,
        unit: "x",
        target: 5,
        status: "amber",
        trend: "up",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
    ],
  },
  {
    id: "audit-compliance",
    name: "Audit and Compliance",
    shortName: "Audit",
    icon: "Shield",
    head: "Head of Audit",
    metrics: [
      {
        id: "risk-operational",
        name: "Operational Risks",
        value: "Moderate",
        status: "amber",
        details: "Drought risk: High | Supply shortage: Low | Equipment failure: Low",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "risk-financial",
        name: "Financial Risk Indicators",
        value: "Low",
        status: "green",
        details: "Liquidity: Good | Credit risk: Low | Market risk: Moderate",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "risk-compliance",
        name: "Compliance Status",
        value: "Compliant",
        status: "green",
        details: "All regulatory requirements met. Next audit: Q3 2024",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
      {
        id: "risk-audit",
        name: "Audit Flags",
        value: 2,
        unit: "open items",
        status: "amber",
        details: "Inventory reconciliation (minor) | Documentation gap (minor)",
        comments: [],
        lastUpdated: STATIC_TIMESTAMP,
      },
    ],
  },
];

// Department scorecard for executive dashboard
export function getDepartmentScorecard(departments: DepartmentData[]) {
  return departments
    .filter((d) => d.id !== "executive")
    .map((dept) => {
      const metrics = dept.metrics;
      const greenCount = metrics.filter((m) => m.status === "green").length;
      const amberCount = metrics.filter((m) => m.status === "amber").length;
      const redCount = metrics.filter((m) => m.status === "red").length;

      let overallStatus: MetricStatus = "green";
      if (redCount > 0) overallStatus = "red";
      else if (amberCount > greenCount) overallStatus = "amber";

      return {
        id: dept.id,
        name: dept.shortName,
        status: overallStatus,
        greenCount,
        amberCount,
        redCount,
      };
    });
}

// Map executive metrics to department sources
export const executiveMetricSources: Record<string, string> = {
  "exec-revenue": "sales-marketing",
  "exec-gross-profit": "finance",
  "exec-net-profit": "finance",
  "exec-sales-volume": "sales-marketing",
  "exec-production-alignment": "operations-manufacturing",
  "exec-inventory-value": "inventory",
  "exec-cash-flow": "finance",
  "exec-debtors": "finance",
  "exec-top-product": "sales-marketing",
};
